#ifndef LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_DEBUGGABLE_H
#define LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_DEBUGGABLE_H

#include "serstream"

class Debuggable {
public:
    virtual String Tag() = 0;
};


#endif //LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_DEBUGGABLE_H
