#ifndef LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_DEBUGGER_H
#define LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_DEBUGGER_H


class Debugger {
public:
    virtual void PrintDebugLog();
};


#endif //LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_DEBUGGER_H
