#ifndef CONFIG_H
#define CONFIG_H

#define RIGHT_MOTOR_PLUS_PIN 2
#define RIGHT_MOTOR_MINUS_PIN 3
#define RIGHT_MOTOR_PWM_PIN 10

#define LEFT_MOTOR_PLUS_PIN 4
#define LEFT_MOTOR_MINUS_PIN 5
#define LEFT_MOTOR_PWM_PIN 11

// A3 == 17
#define LEFT_PHOTO_REFLECTOR_PIN 17
#define RIGHT_PHOTO_REFLECTOR_PIN 17
#define FRONT_PHOTO_REFLECTOR_PIN 17

#endif //CONFIG_H
