@startuml
'https://plantuml.com/class-diagram

abstract class CarBuilder {
+ SetLeftWheel(wheel: Wheel*)
+ SetRightWheel(wheel: Wheel*)
+ GetLeftWheel(): Wheel*
+ GetRightWheel(): Wheel*
+ Build(): Car*
# left_wheel_: Wheel*
# right_wheel_: Wheel*
}

CarBuilder ..> Car
CarBuilder ..> Wheel
Car ..> CarBuilder

abstract class Car {
# left_wheel_: Wheel*
# right_wheel_: Wheel*
+ Car(builder: CarBuilder*)
+ UpdateSensors()
+ Think()
+ Act()
}

class LineTraceCar {
- brain_: LineTraceBrain*
- front_mid_reflector_: PhotoReflector*
- front_left_reflector_: PhotoReflector*
- front_right_reflector_: PhotoReflector*
- back_mid_reflector_: PhotoReflector*
- back_left_reflector_: PhotoReflector*
- back_right_reflector_: PhotoReflector*
- instruction_: Instruction*
+ LineTraceCar(builder: LineTraceCarBuilder*)
- CollectCarState(): LineTraceCarState
}

class LineTraceCarState {
+ left_wheel_speed_: int
+ right_wheel_speed_: int
+ left_wheel_direction_: MoveDirection
+ right_wheel_direction_: MoveDirection
+ front_mid_reflector_color_: BinaryColor
+ front_left_reflector_color_: BinaryColor
+ front_right_reflector_color_: BinaryColor
+ back_mid_reflector_color_: BinaryColor
+ back_left_reflector_color_: BinaryColor
+ back_right_reflector_color_: BinaryColor
+ front_mid_reflector_raw_: int
+ front_left_reflector_raw_: int
+ front_right_reflector_raw_: int
+ back_mid_reflector_raw_: int
+ back_left_reflector_raw_: int
+ back_right_reflector_raw_: int
+ IsAnyBlack(): bool
+ IsAnyWhite(): bool
+ IsAllBlack(): bool
+ IsAllWhite(): bool
+ IsAnyFrontBlack(): bool
+ IsAnyBackBlack(): bool
+ IsAnyFrontWhite(): bool
+ IsAnyBackWhite(): bool
+ IsAllFrontBlack(): bool
+ IsAllBackBlack(): bool
+ IsAllFrontWhite(): bool
+ IsAllBackWhite(): bool
}

abstract class LineTraceBrain {
+ SetCurrentCarState(car_state: LineTraceCarState)
# current_car_state_: LineTraceCarState
# activity_state_: LineTraceActivityState
# Ready(): Instruction*
# Search(): Instruction*
# Trace(): Instruction*
# ReadyBack(): Instruction*
# SearchBack(): Instruction*
# TraceBack(): Instruction*
}

enum LineTraceActivityState {
    ready
    searching
    tracing
    readyBack
    searchingBack
    tracingBack
    finished
}

class LineTraceCarBuilder {
- brain_: LineTraceBrain*
- front_mid_reflector_: PhotoReflector*
- front_left_reflector_: PhotoReflector*
- front_right_reflector_: PhotoReflector*
- back_mid_reflector_: PhotoReflector*
- back_left_reflector_: PhotoReflector*
- back_right_reflector_: PhotoReflector*
+ SetBrain(brain: LineTraceBrain*)
+ SetFrontMidReflector(reflector: PhotoReflector*)
+ SetFrontLeftReflector(reflector: PhotoReflector*)
+ SetFrontRightReflector(reflector: PhotoReflector*)
+ SetBackMidReflector(reflector: PhotoReflector*)
+ SetBackLeftReflector(reflector: PhotoReflector*)
+ SetBackRightReflector(reflector: PhotoReflector*)
+ GetBrain(): LineTraceBrain*
+ GetFrontMidReflector(): PhotoReflector*
+ GetFrontLeftReflector(): PhotoReflector*
+ GetFrontRightReflector(): PhotoReflector*
+ GetBackMidReflector(): PhotoReflector*
+ GetBackLeftReflector(): PhotoReflector*
+ GetBackRightReflector(): PhotoReflector*
}

class LineTraceGoAndBackBrain {
+ LineTraceGoAndBackBrain(base_speed: int, torque_force: int)
- base_speed_: int
- torque_force_: int
}

LineTraceGoAndBackBrain --|> LineTraceBrain
LineTraceCar --|> Car
LineTraceCar ..> LineTraceCarState
LineTraceCar ..> LineTraceBrain
LineTraceCar ..> PhotoReflector
LineTraceCar ..> Instruction
LineTraceBrain ..|> Brain
LineTraceBrain ..> LineTraceActivityState
LineTraceCarBuilder ..> PhotoReflector
LineTraceCarBuilder ..> LineTraceBrain
LineTraceCarBuilder --|> CarBuilder

Car ..> Wheel

interface Brain {
CalculateNextInstruction(): Instruction*
}

Brain ..> Instruction

class Instruction {
+ runCoroutine(): int
+ Setup(left_wheel: Wheel*, right_wheel: Wheel*)
+ SetMode(mode: InstructionMode)
+ Mode(): InstructionMode
# left_wheel_: Wheel*
# right_wheel: Wheel*
# mode_: InstructionMode
}

Instruction ..> InstructionMode

enum InstructionMode {
    none
    interrupt
}

class Wheel {
- plus_pin_: int
- minus_pin_: int
- pwm_pin_: int
- speed_: int
- direction_: MoveDirection
+ UpdateSpeed(speed: int)
+ UpdateDeltaSpeed(speed: int)
+ UpdateDirection(direction: MoveDirection)
+ Speed(): int
+ Direction(): MoveDirection
}

Wheel ..> MoveDirection

enum MoveDirection {
    forward
    backward
}

class Sensor {
- pin_: int
- value_: int
+ Sensor(pin: int)
+ Update()
+ RawValue(): int
}

class PhotoReflector {
- theta_: int
+ PhotoReflector(pin: int, theta: int)
+ Value(): BinaryColor
}

enum BinaryColor {
    black, white
}


PhotoReflector --|> Sensor
PhotoReflector ..> BinaryColor

@enduml