#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h>

#define RIGHT_MOTOR_PLUS_PIN 2
#define RIGHT_MOTOR_MINUS_PIN 3
#define RIGHT_MOTOR_PWM_PIN 10

#define LEFT_MOTOR_PLUS_PIN 4
#define LEFT_MOTOR_MINUS_PIN 5
#define LEFT_MOTOR_PWM_PIN 11

#define RIGHT_PHOTO_REFLECTOR_PIN A3
#define FRONT_PHOTO_REFLECTOR_PIN A4
#define LEFT_PHOTO_REFLECTOR_PIN A5

#define PHOTO_REFLECTOR_THRESHOLD 500

#endif //CONFIG_H
