#ifndef LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_CONTROLLER_H
#define LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_CONTROLLER_H

/**
 * 制御クラスのインタフェース
 */
class Controller {
public:
    virtual void OperateCar();
};


#endif //LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_CONTROLLER_H
