#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h>

#define BASE_SPEED 130
#define LR_SENSOR_DIFF -4
#define TURN_SPEED 140
#define TRACE_MODE goBack
#define P 0.05
#define D 0.0
#define MAX_MANIPULATION 50

#define RIGHT_MOTOR_PLUS_PIN 2
#define RIGHT_MOTOR_MINUS_PIN 3
#define RIGHT_MOTOR_PWM_PIN 10

#define LEFT_MOTOR_PLUS_PIN 4
#define LEFT_MOTOR_MINUS_PIN 5
#define LEFT_MOTOR_PWM_PIN 11

#define RIGHT_PHOTO_REFLECTOR_PIN A0
#define MID_PHOTO_REFLECTOR_PIN A1
#define LEFT_PHOTO_REFLECTOR_PIN A2

#define PHOTO_REFLECTOR_THRESHOLD 500

#endif //CONFIG_H
