#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h>

#define BASE_SPEED 110
#define FORWARD_TORQUE 20
#define BACKWARD_TORQUE 10

#define RIGHT_MOTOR_PLUS_PIN 2
#define RIGHT_MOTOR_MINUS_PIN 3
#define RIGHT_MOTOR_PWM_PIN 10

#define LEFT_MOTOR_PLUS_PIN 4
#define LEFT_MOTOR_MINUS_PIN 5
#define LEFT_MOTOR_PWM_PIN 11

#define FRONT_RIGHT_PHOTO_REFLECTOR_PIN A0
#define FRONT_MID_PHOTO_REFLECTOR_PIN A1
#define FRONT_LEFT_PHOTO_REFLECTOR_PIN A2

#define BACK_RIGHT_PHOTO_REFLECTOR_PIN A3
#define BACK_MID_PHOTO_REFLECTOR_PIN A4
#define BACK_LEFT_PHOTO_REFLECTOR_PIN A5

#define PHOTO_REFLECTOR_THRESHOLD 500

#endif //CONFIG_H
