#ifndef LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_INSTRUCTION_MODE_H
#define LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_INSTRUCTION_MODE_H

enum InstructionMode {
    none, interrupt,
};

#endif //LABORATORY_WORK_IN_INFORMATION_ENGINEERING_III_INSTRUCTION_MODE_H
